version: '3.2'

services:
  backend_node:
    image: "node:12"
    volumes:
      - "./backend_node/:/home/node/app"
    environment:
      - HOST=0.0.0.0  # listen on all interfaces
    expose:
      - "8082"
    command: bash -c "
      npm i -g @adonisjs/cli && npm ci && cp .env.example .env && adonis key:generate && npm run serve
      "
    working_dir: /home/node/app
    ports:
      - 8082:8082
    links:
      - redis
    depends_on:
      - redis
    networks:
      - challenge

  frontend:
    image: "node:12"
    volumes:
      - "./frontend/:/home/node/app"
    expose:
      - "8080"
    command: bash -c "
      npm install -g @quasar/cli && yarn && quasar dev
      "
    working_dir: /home/node/app
    ports:
      - 8080:8080
    depends_on:
      - backend_node
    networks:
      - challenge

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - redis:/data
    networks:
      - challenge


networks:
  challenge:
    driver: bridge

volumes:
  redis:

